spring:
  application:
    name: spring-boot-security-auth
    jackson:
      property-naming-strategy: SNAKE_CASE
    flyway:
      locations: classpath:/db/migration
      schemas: employee
      baselineOnMigrate: true
      enabled: true
  jpa:
    show-sql: true
